package com.example.card_deck_memory

val DEFAULT_CARDS = listOf(
    R.drawable.cuori_a,
    R.drawable.cuori_2,
    R.drawable.cuori_3,
    R.drawable.cuori_4,
    R.drawable.cuori_5,
    R.drawable.cuori_6,
    R.drawable.cuori_7,
    R.drawable.cuori_8,
    R.drawable.cuori_9,
    R.drawable.cuori_10,
    R.drawable.cuori_j,
    R.drawable.cuori_q,
    R.drawable.cuori_k,

    R.drawable.quadri_a,
    R.drawable.quadri_2,
    R.drawable.quadri_3,
    R.drawable.quadri_4,
    R.drawable.quadri_5,
    R.drawable.quadri_6,
    R.drawable.quadri_7,
    R.drawable.quadri_8,
    R.drawable.quadri_9,
    R.drawable.quadri_10,
    R.drawable.quadri_j,
    R.drawable.quadri_q,
    R.drawable.quadri_k,

    R.drawable.fiori_a,
    R.drawable.fiori_2,
    R.drawable.fiori_3,
    R.drawable.fiori_4,
    R.drawable.fiori_5,
    R.drawable.fiori_6,
    R.drawable.fiori_7,
    R.drawable.fiori_8,
    R.drawable.fiori_9,
    R.drawable.fiori_10,
    R.drawable.fiori_j,
    R.drawable.fiori_q,
    R.drawable.fiori_k,

    R.drawable.picche_a,
    R.drawable.picche_2,
    R.drawable.picche_3,
    R.drawable.picche_4,
    R.drawable.picche_5,
    R.drawable.picche_6,
    R.drawable.picche_7,
    R.drawable.picche_8,
    R.drawable.picche_9,
    R.drawable.picche_10,
    R.drawable.picche_j,
    R.drawable.picche_q,
    R.drawable.picche_k
)